-
  branches:
    only:
      - master
  deploy:
    provider: NuGet
    api_key:
      secure: z3OZoWsfl2Axbs0S3ojUr2scRja69t3mNqAFrT2Uc48wow+4jyvIBY08g1hO7nyL
    skip_symbols: false
    symbol_server:  # fix up when appveyor get nuget symbol support
    artifact: /.*\.nupkg/
-
  version: 1.0.{build}
  image:
    - Ubuntu1604

  nuget:
    disable_publish_on_pr: true

  build_script:
    - cmd: dotnet pack src/hash-identity/hash-identity.csproj -c Release --output output

  test_script:
    - cmd: dotnet test

  artifacts:
    - path: 'output\**\*.nupkg'
    - path: 'output\**\*.snupkg'

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'
